### ISSUE TITLE
Add styling and data for TV routes

### ISSUE THREAD

**Issue by macjabeth** [macjabeth/showbunny#57]
Styling and data should be inspired by the design spec (see README.md).

**Tasks**
- [ ] Render TV show data
- [ ] Show seasons and episodes
- [ ] Style displayed data for mobile screens
- [ ] Style displayed data for tablet & desktop screens

**Comment by irffanasiff** [comment]
Hi I want to work on this issue

**Comment by macjabeth** [comment]
> Hi I want to work on this issue

Go for it!
