### ISSUE TITLE
Add styling and data for Movie routes

### ISSUE THREAD

**Issue by macjabeth** [macjabeth/showbunny#58]
Styling and data should be inspired by the design spec (see README.md).

**Tasks**
- [x] Render Movie data
- [x] Style displayed data for mobile screens
- [ ] Style displayed data for tablet & desktop screens
